swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  paths:
  /user/transactions/{accountId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Get User Account Transactions
      description: Retrieve all transactions for the specified account and given month
      parameters:
        - in: path
          name: accountId
          required: true
          type: integer
          description: ID of the Account
        - in: query
          name: month
          required: true
          type: integer
          description: Month for which transactions are requested (1 for January, 2 for February, etc.)
      produces:
        - application/json
      responses:
        '200':
          description: User account transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '404':
          description: Account not found or no transactions for the specified month
        '500':
          description: Internal Server Error
  /transactions/deleteCategory/{id}:
    delete:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Delete Transaction Category
      description: Delete the category of a specific transaction
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          description: ID of the Transaction
      produces:
        - application/json
      responses:
        '200':
          description: Transaction category deleted successfully
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
  /transactions/deleteNote/{id}:
    delete:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Delete Transaction Note
      description: Delete the note of a specific transaction
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          description: ID of the Transaction
      produces:
        - application/json
      responses:
        '200':
          description: Transaction note deleted successfully
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
  /transactions/updateCategory/{id}:
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Update Transaction Category
      description: Update the category of a specific transaction
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          description: ID of the Transaction
        - in: body
          name: body
          description: Update transaction category
          required: true
          schema:
            type: object
            properties:
              newCategoryId:
                type: integer
                description: ID of the new Category
      produces:
        - application/json
      responses:
        '200':
          description: Category updated successfully
        '400':
          description: Invalid Fields      
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
  /transactions/updateNote/{id}:
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Update Transaction Note
      description: Update the note of a specific transaction
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          description: ID of the Transaction
        - in: body
          name: body
          description: Update transaction note
          required: true
          schema:
            type: object
            properties:
              newNote:
                type: string
                description: New Note of the Transaction
      produces:  
        - application/json
      responses:
        '200':
          description: Note updated successfully
        '400':
          description: Invalid Fields      
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email
